Fix sat URL in mockData_v1.csv
Replace hard coded path with github based URL:
```
sed -i -e 's#/Users/leannahouse/Documents/research/imageomics/quest/andromeda2023/mockData/#https://raw.githubusercontent.com/Imageomics/Andromeda/main/datasets/testData/#' mockData_v1.csv
```

The URLs will only work once this commit is merged into the
main branch. Additionally the CSV has several problems when
used with the latest version of Andoromeda(branch react-v2).
1) The 'iNat_url' column has no URL for iNat_label=p6. This causes
errors when trying to visualize. So only the 'sat_url' column
for URL works.
2) The sat_maxRed, sat_maxGreen, and sat_maxBlue columns cause a
error:
KeyError: "['sat_maxRed', 'sat_maxGreen', 'sat_maxBlue'] not in index"
These columns must be deselected for Andromeda to work.